__collection-name__: user-parameter-file

# Jpos_Controller
file_name : "jpos_user_parameters.yaml"

# Cheetah_Controller
#file_name : "milab-user-parameters.yaml"
#file_name : "mc-mit-ctrl-user-parameters.yaml"