# Generated on 04/23/2021 by WANG YINUO
__collection-name__: user-parameters
# Parameters for JOINT PD CONTROL

max_tau : 45.
max_iter : 15000
#　motor move param
move_range : 0.2
move_offset : 0.0
# motor selection
leg_enable : [1,0,0,0]
joint_enable : [1,1,1]
# control params
kp : [350,350,450]
kd : [8,13,15]
tau_ff : 0.0

zero : 0
calibrate : 0


# Tip: Jpos controller can not run normally when milab-robot-parameter cheater_mode = 1 !! keep it = 0